CREATE TABLE TR_NEWS_VERSION(
ID_SOURCE NUMBER,
START_DATE DATE,
END_DATE DATE,
STATUS VARCHAR2(1),
TITLE VARCHAR2(1000),
CONTENT VARCHAR2(4000),
PUBLICATION_DATE DATE,
AUTHOR VARCHAR2(500)
)
