CREATE TABLE STG_TR_NEWS(
ID NUMBER,
DATE_CREATED DATE,
DATE_MODIFIED DATE,
TITLE VARCHAR2(1000),
CONTENT VARCHAR2(4000),
PUBLICATION_DATE DATE,
AUTHOR VARCHAR2(500),
CATEGORY VARCHAR2(1000)
)

